# Class Constants
CLASS_WARRIOR   = 1
CLASS_PALADIN   = 2
CLASS_HUNTER    = 3
CLASS_ROGUE     = 4
CLASS_PRIEST    = 5
CLASS_DEATH_KNIGHT = 6
CLASS_SHAMAN    = 7
CLASS_MAGE      = 8
CLASS_WARLOCK   = 9
CLASS_MONK      = 10
CLASS_DRUID     = 11
CLASS_DEMON_HUNTER = 12

# Class Names
CLASS_WARRIOR_NAME = "Warrior"
CLASS_PALADIN_NAME = "Paladin"
CLASS_HUNTER_NAME = "Hunter"
CLASS_ROGUE_NAME = "Rogue"
CLASS_PRIEST_NAME = "Priest"
CLASS_DEATH_KNIGHT_NAME = "Death Knight"
CLASS_SHAMAN_NAME = "Shaman"
CLASS_MAGE_NAME = "Mage"
CLASS_WARLOCK_NAME = "Warlock"
CLASS_MONK_NAME = "Monk"
CLASS_DRUID_NAME = "Druid"
CLASS_DEMON_HUNTER_NAME = "Demon Hunter"

# WoW Colours
CLASS_WARRIOR_COLOUR    = 0xC796E
CLASS_PALADIN_COLOUR    = 0xF58CBA
CLASS_HUNTER_COLOUR     = 0xABD473
CLASS_ROGUE_COLOUR      = 0xFFF569
CLASS_PRIEST_COLOUR    = 0xFFFFFF
CLASS_DEATH_KNIGHT_COLOUR = 0xC41F3B
CLASS_SHAMAN_COLOUR     = 0x0070DE
CLASS_MAGE_COLOUR       = 0x69CCF0
CLASS_WARLOCK_COLOUR    = 0x9482C9
CLASS_MONK_COLOUR       = 0x00FF96
CLASS_DRUID_COLOUR      = 0xFF7D0A
CLASS_DEMON_HUNTER_COLOUR = 0xA330C9